// Mocks generated by Mockito 5.4.6 from annotations
// in key_wallet_app/test/UnitTest/screens/new_wallet_creation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i7;

import 'package:flutter_nfc_kit/flutter_nfc_kit.dart' as _i4;
import 'package:key_wallet_app/models/wallet.dart' as _i6;
import 'package:key_wallet_app/services/i_nfc_service.dart' as _i2;
import 'package:key_wallet_app/services/i_wallet_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [INfcService].
///
/// See the documentation for Mockito's code generation for more information.
class MockINfcService extends _i1.Mock implements _i2.INfcService {
  MockINfcService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> checkAvailability() =>
      (super.noSuchMethod(
            Invocation.method(#checkAvailability, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.NFCTag?> fetchNfcData() =>
      (super.noSuchMethod(
            Invocation.method(#fetchNfcData, []),
            returnValue: _i3.Future<_i4.NFCTag?>.value(),
          )
          as _i3.Future<_i4.NFCTag?>);
}

/// A class which mocks [IWalletService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIWalletService extends _i1.Mock implements _i5.IWalletService {
  MockIWalletService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  List<_i6.Wallet> get wallets =>
      (super.noSuchMethod(
            Invocation.getter(#wallets),
            returnValue: <_i6.Wallet>[],
          )
          as List<_i6.Wallet>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<void> fetchUserWallets(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserWallets, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> checkIfWalletExists(String? hBytes, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#checkIfWalletExists, [hBytes, userId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> generateAndAddWallet(
    String? userId,
    String? email,
    String? walletName,
    _i7.Color? selectedColor,
    String? hBytes,
    String? standard,
    String? device,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateAndAddWallet, [
              userId,
              email,
              walletName,
              selectedColor,
              hBytes,
              standard,
              device,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteWalletDBandList(_i6.Wallet? wallet) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWalletDBandList, [wallet]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateBalance(String? walletId, double? newBalance) =>
      (super.noSuchMethod(
            Invocation.method(#updateBalance, [walletId, newBalance]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NFCTag].
///
/// See the documentation for Mockito's code generation for more information.
class MockNFCTag extends _i1.Mock implements _i4.NFCTag {
  MockNFCTag() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.NFCTagType get type =>
      (super.noSuchMethod(
            Invocation.getter(#type),
            returnValue: _i4.NFCTagType.iso7816,
          )
          as _i4.NFCTagType);

  @override
  String get standard =>
      (super.noSuchMethod(
            Invocation.getter(#standard),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#standard),
            ),
          )
          as String);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
