// Mocks generated by Mockito 5.4.6 from annotations
// in key_wallet_app/test/UnitTest/screens/wallet_recover_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_nfc_kit/flutter_nfc_kit.dart' as _i4;
import 'package:key_wallet_app/services/i_nfc_service.dart' as _i2;
import 'package:key_wallet_app/services/i_recover_service.dart' as _i5;
import 'package:key_wallet_app/services/i_secure_storage.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [INfcService].
///
/// See the documentation for Mockito's code generation for more information.
class MockINfcService extends _i1.Mock implements _i2.INfcService {
  MockINfcService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> checkAvailability() =>
      (super.noSuchMethod(
            Invocation.method(#checkAvailability, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.NFCTag?> fetchNfcData() =>
      (super.noSuchMethod(
            Invocation.method(#fetchNfcData, []),
            returnValue: _i3.Future<_i4.NFCTag?>.value(),
          )
          as _i3.Future<_i4.NFCTag?>);
}

/// A class which mocks [IRecoverService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRecoverService extends _i1.Mock implements _i5.IRecoverService {
  MockIRecoverService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> checkIfRight(String? publicKey, String? privateKeyString) =>
      (super.noSuchMethod(
            Invocation.method(#checkIfRight, [publicKey, privateKeyString]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [ISecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockISecureStorage extends _i1.Mock implements _i6.ISecureStorage {
  MockISecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> writeSecureData(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#writeSecureData, [key, value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> readSecureData(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#readSecureData, [key]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteSecureData(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSecureData, [key]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [NFCTag].
///
/// See the documentation for Mockito's code generation for more information.
class MockNFCTag extends _i1.Mock implements _i4.NFCTag {
  MockNFCTag() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.NFCTagType get type =>
      (super.noSuchMethod(
            Invocation.getter(#type),
            returnValue: _i4.NFCTagType.iso7816,
          )
          as _i4.NFCTagType);

  @override
  String get standard =>
      (super.noSuchMethod(
            Invocation.getter(#standard),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#standard),
            ),
          )
          as String);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
