// Mocks generated by Mockito 5.4.6 from annotations
// in key_wallet_app/test/UnitTest/screens/wallet_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i6;

import 'package:cloud_firestore/cloud_firestore.dart' as _i8;
import 'package:key_wallet_app/models/wallet.dart' as _i5;
import 'package:key_wallet_app/services/i_chat_service.dart' as _i7;
import 'package:key_wallet_app/services/i_secure_storage.dart' as _i2;
import 'package:key_wallet_app/services/i_wallet_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ISecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockISecureStorage extends _i1.Mock implements _i2.ISecureStorage {
  MockISecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> writeSecureData(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#writeSecureData, [key, value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> readSecureData(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#readSecureData, [key]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteSecureData(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSecureData, [key]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [IWalletService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIWalletService extends _i1.Mock implements _i4.IWalletService {
  MockIWalletService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  List<_i5.Wallet> get wallets =>
      (super.noSuchMethod(
            Invocation.getter(#wallets),
            returnValue: <_i5.Wallet>[],
          )
          as List<_i5.Wallet>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<void> fetchUserWallets(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserWallets, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> checkIfWalletExists(String? hBytes, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#checkIfWalletExists, [hBytes, userId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> generateAndAddWallet(
    String? userId,
    String? email,
    String? walletName,
    _i6.Color? selectedColor,
    String? hBytes,
    String? standard,
    String? device,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateAndAddWallet, [
              userId,
              email,
              walletName,
              selectedColor,
              hBytes,
              standard,
              device,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteWalletDBandList(_i5.Wallet? wallet) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWalletDBandList, [wallet]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateBalance(String? walletId, double? newBalance) =>
      (super.noSuchMethod(
            Invocation.method(#updateBalance, [walletId, newBalance]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [IChatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIChatService extends _i1.Mock implements _i7.IChatService {
  MockIChatService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<Map<String, dynamic>>> getConversationsStream(
    String? senderWalletId,
    String? localKeyIdentifier,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationsStream, [
              senderWalletId,
              localKeyIdentifier,
            ]),
            returnValue: _i3.Stream<List<Map<String, dynamic>>>.empty(),
          )
          as _i3.Stream<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> createConversationIfNotExists(
    _i5.Wallet? wallet1,
    _i5.Wallet? wallet2,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createConversationIfNotExists, [
              wallet1,
              wallet2,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> sendMessage(
    _i5.Wallet? receiverWallet,
    _i5.Wallet? senderWallet,
    String? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [
              receiverWallet,
              senderWallet,
              message,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i8.QuerySnapshot<Object?>> getMessages(
    _i5.Wallet? senderWallet,
    _i5.Wallet? receiverWallet,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [senderWallet, receiverWallet]),
            returnValue: _i3.Stream<_i8.QuerySnapshot<Object?>>.empty(),
          )
          as _i3.Stream<_i8.QuerySnapshot<Object?>>);

  @override
  _i3.Future<String?> translateMessage(String? message, _i5.Wallet? wallet) =>
      (super.noSuchMethod(
            Invocation.method(#translateMessage, [message, wallet]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}
