// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkFg2QfYhIE8k3QeRIElSXGLOolVYG2Mo',
    appId: '1:806163097376:web:1a7cb34e906f869cead945',
    messagingSenderId: '806163097376',
    projectId: 'keywalletapp',
    authDomain: 'keywalletapp.firebaseapp.com',
    storageBucket: 'keywalletapp.firebasestorage.app',
    measurementId: 'G-XQEESG0K87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkFg2QfYhIE8k3QeRIElSXGLOolVYG2Mo',
    appId: '1:806163097376:android:67723fc576b3e00fead945',
    messagingSenderId: '806163097376',
    projectId: 'keywalletapp',
    storageBucket: 'keywalletapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkFg2QfYhIE8k3QeRIElSXGLOolVYG2Mo',
    appId: '1:806163097376:ios:8e571cd26a6290cdead945',
    messagingSenderId: '806163097376',
    projectId: 'keywalletapp',
    storageBucket: 'keywalletapp.firebasestorage.app',
    iosBundleId: 'me.gabrieledipietro.keyWalletApp',
  );

}