// Mocks generated by Mockito 5.4.6 from annotations
// in key_wallet_app/test/UnitTest/WidgetTest/build_user_input_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cloud_firestore/cloud_firestore.dart' as _i5;
import 'package:key_wallet_app/models/wallet.dart' as _i4;
import 'package:key_wallet_app/services/i_chat_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IChatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIChatService extends _i1.Mock implements _i2.IChatService {
  MockIChatService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<Map<String, dynamic>>> getConversationsStream(
    String? senderWalletId,
    String? localKeyIdentifier,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationsStream, [
              senderWalletId,
              localKeyIdentifier,
            ]),
            returnValue: _i3.Stream<List<Map<String, dynamic>>>.empty(),
          )
          as _i3.Stream<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> createConversationIfNotExists(
    _i4.Wallet? wallet1,
    _i4.Wallet? wallet2,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createConversationIfNotExists, [
              wallet1,
              wallet2,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> sendMessage(
    _i4.Wallet? receiverWallet,
    _i4.Wallet? senderWallet,
    String? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [
              receiverWallet,
              senderWallet,
              message,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i5.QuerySnapshot<Object?>> getMessages(
    _i4.Wallet? senderWallet,
    _i4.Wallet? receiverWallet,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [senderWallet, receiverWallet]),
            returnValue: _i3.Stream<_i5.QuerySnapshot<Object?>>.empty(),
          )
          as _i3.Stream<_i5.QuerySnapshot<Object?>>);

  @override
  _i3.Future<String?> translateMessage(String? message, _i4.Wallet? wallet) =>
      (super.noSuchMethod(
            Invocation.method(#translateMessage, [message, wallet]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}
