# File: .github/workflows/dart.yml

name: Flutter CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Configura Flutter (QUESTO AGGIUNGE 'flutter' e 'dart' al PATH)
      # Questo step risolve l'errore 'command not found'.
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.9.2' # Assicurati che questa versione sia valida

      # Rimuovi tutte le azioni 'dart-lang/setup-dart' che avevi,
      # poiché l'azione Flutter gestisce già l'SDK Dart appropriato.

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        # Usa 'flutter analyze' per i progetti Flutter
        run: flutter analyze

      - name: Run tests
        run: flutter test